motion_planner:
  ros__parameters:
    behavior: "LIGHT_FOLLOWER"
    run_behavior: true 
    max_advance: 0.05 # METERS
    max_turn_angle: 0.7805 # RADIANS
    light_threshold: 3600.0
    laser_threshold: 0.125
    step: 0
    max_steps: 150
