motion_planner:
  ros__parameters:
    behavior: "USER_SM"
    run_behavior: true
    max_advance: 1.0 # METERS
    max_turn_angle: 1.0 # RADIANS
    light_threshold: 2.0
    step: 0
    max_steps: 10
