motion_planner:
  ros__parameters:
    behavior: "USER_SM"
    run_behavior: false
    max_advance: 0.03 # METERS
    max_turn_angle: 0.5 # RADIANS
    light_threshold: 0.04503
    laser_threshold: 0.3
    step: 0
    max_steps: 35
