motion_planner:
  ros__parameters:
    behavior: "USER_SM"
    run_behavior: true 
    max_advance: 0.05 # METERS
    max_turn_angle: 0.7805 # RADIANS
    light_threshold: 0.04503
    laser_threshold: 0.125
    step: 0
    max_steps: 35
