colors = {
    'background': '#EDEDED',
    'entry_backgroud': '#FBFBFB',
    'entry_foreground': '#37363A',
    'titles': '#303133',
    'menu': '#ECECEC',
    'menu_button': '#375ACC',
    'menu_button_font': '#FFFFFF',
    'obstacle_inner': '#447CFF',
    'obstacles_outline': '#216E7D',
    'button': '#1373E6',
    'button_font': '#FFFFFF',
    'canvas': '#FFFFFF',
    'grid': '#D1D2D4',
    'wheel': '#404000',
    'robot': '#F7CE3F',
    'hokuyo': '#4F58DB',
    'arrow': '#1AAB4A',
    'head': '#1AAB4A',
    'laser': '#00DD41',
    'warn_light': '#F7FD2A',
    'warn_strong': '#EEF511',
    'error_light': '#FA0A0A',
    'error_strong': '#E10B0B'
}
