colors = {
    'background': '#EDEDED',
    'entrybackgroud': '#FBFBFB',
    'entryforeground': '#37363A',
    'titles': '#303133',
    'menu': '#ECECEC',
    'menuButon': '#375ACC',
    'menuButonFont': '#FFFFFF',
    'obstacleInner': '#447CFF',
    'obstaclesOutline': '#216E7D',
    'button': '#1373E6',
    'buttonFont': '#FFFFFF',
    'canvas': '#FFFFFF',
    'grid': '#D1D2D4',
    'wheel': '#404000',
    'robot': '#F7CE3F',
    'hokuyo': '#4F58DB',
    'arrow': '#1AAB4A',
    'laser': '#00DD41',
    'warnLight': '#F7FD2A',
    'warnStrong': '#EEF511',
    'errorLight': '#FA0A0A',
    'errorStrong': '#E10B0B'
}
